### ISSUE TITLE
[CY-2992] Ask: Where should "esversion" be added?

### ISSUE THREAD

**Issue by TheColdPot** [codacy/codacy-analysis-cli#313]
In my workflow, it says
```
`'class' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).` in FILENAME:70 (iterator)
```
So, where should "esversion" be added?
I think can add this to documation

**Comment by TheColdPot** [comment]
Add in tool? Like this:
```yaml
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@1.0.1
        with:
          # The name of the tool to analyze the code
          tool: 'esversion: 6'
```
