### ISSUE TITLE
[CY-3085] CLI cannot use .eslintrc configuration

### ISSUE THREAD

**Issue by TheColdPot** [codacy/codacy-analysis-cli#323]
In <app.codacy.com>, the configuration file needs to be `.eslintrc`, but in CLI, this does not work:
```json
// .eslintrc
{
  "parseOptions": {
    "ecmaVersion": 6
  }
}
```
If it is a CLI problem, can `.eslintrc` also be used as the configuration object for detection? My current processing method is that `.eslintrc` and `.jshintrc` exist at the same time

**Comment by TheColdPot** [comment]
Resolved:
```yaml
uses: codacy/codacy-analysis-cli-action@1.1.0
with:
  tool: ESLint
```
