### ISSUE TITLE
[TS-197] QUESTION: How to output an alert with the complete file path?  

### ISSUE THREAD

**Issue by AntonioFalcaoJr** [codacy/codacy-analysis-cli#470]
```yml
      - name: Run Analysis
        uses: codacy/codacy-analysis-cli-action@v4.2.0
        with:
          directory: ${{ inputs.path }}
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          tool: sonarscharp
          gh-code-scanning-compat: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: results.sarif
```

![image](https://user-images.githubusercontent.com/20262424/214859162-ed25ce0a-f3af-4a85-b510-df666b25bf31.png)
